# Generated by Django 6.0.5 on 2026-05-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('registrator', 'Медицинский регистратор'), ('doctor', 'Врач'), ('admin', 'Администратор'), ('patient', 'Пациент')], default='registrator', max_length=20, verbose_name='Роль'),
        ),
    ]
